fst_num = input('Enter your first whole number= ')
sec_num = input('Enter your second  number= ')
sum = int(fst_num) + float(sec_num)
print('sum=' , sum)
mul =   int(fst_num) * float(sec_num)
print('multiplicaiton= ' ,  mul)
